version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  notes-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres:
    name: nest-prisma-docker-db
